<a href="https://colab.research.google.com/github/vivekpatel1204/ML-PROJECT/blob/main/ML_FINAL(L).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')



In [ ]:
data = pd.read_csv('password_data.csv', on_bad_lines='skip')


In [ ]:
data


password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
...              ...       ...
669635    10redtux10         1
669636     infrared1         1
669637  184520socram         1
669638     marken22a         1
669639      fxx4pw4g         1

[669640 rows x 2 columns]

Statistical Analysis

In [ ]:
import statistics

In [ ]:
mean=data['strength'].mean()
print('mean of strength',mean)

mean of strength 0.990196224837226


In [ ]:
median_value = data['strength'].median()
print('median of strength',median_value)

median of strength 1.0


In [ ]:
mode_value = data['strength'].mode()
print('mode of strength',mode_value)

mode of strength 0    1
Name: strength, dtype: int64


In [ ]:
col_range = data['strength'].max() - data['strength'].min()
print('the range is:',col_range)

the range is: 2


In [ ]:
variance = data['strength'].var()
print('the variance is:',variance)

the variance is: 0.2580116125495326


In [ ]:
stan_dev = data['strength'].std()
print('the standard deviation:',stan_dev)

the standard deviation: 0.5079484349316696


Pre-processing

In [ ]:
data['strength'].unique()


array([1, 2, 0])

In [ ]:
data.isna().sum()


password    1
strength    0
dtype: int64

In [ ]:
data.dropna(inplace=True)


In [ ]:
data.isna().sum()


password    0
strength    0
dtype: int64

In [ ]:
password_array = np.array(data)


In [ ]:
password_array


array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [ ]:
import random
random.shuffle(password_array)

In [ ]:
x = [labels[0] for labels in password_array]
y = [labels[1] for labels in password_array]

In [ ]:
def word_divide(inputs):
    c = []
    for i in inputs:
        c.append(i)
    return c

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(tokenizer=word_divide)
X = vectorizer.fit_transform(x)

In [ ]:
X.shape

(669639, 126)

In [ ]:
vectorizer.get_feature_names_out()

array(['\x04', '\x05', '\x06', '\x08', '\x0e', '\x10', '\x11', '\x12',
       '\x16', '\x17', '\x19', '\x1b', '\x1c', '\x1e', ' ', '!', '"', '#',
       '$', '%', '&', '(', ')', '*', '+', '-', '.', '/', '0', '1', '2',
       '3', '4', '5', '6', '7', '8', '9', ';', '<', '=', '>', '?', '@',
       '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
       'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '\x7f', '\xa0',
       '¨', '«', '°', '±', '³', '´', 'µ', '·', 'º', '¼', '¾', '¿', 'ß',
       'à', 'á', 'â', 'ä', 'å', 'æ', 'è', 'é', 'ê', 'í', 'ï', 'ð', 'ñ',
       'ò', 'ó', 'ô', 'õ', 'ö', '÷', 'ú', 'û', 'ü', 'ý', 'þ', 'ÿ', 'œ',
       '—', '‚', '‡', '‹', '›'], dtype=object)

In [ ]:
first_document_vector = X[0]
first_document_vector

<1x126 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
first_document_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56689989],
        [0.        ],
        [0.59129313],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [ ]:
df = pd.DataFrame(first_document_vector.T.todense(),index=vectorizer.get_feature_names_out(),columns=['TF-IDF'])
df

TF-IDF
      0.0
      0.0
      0.0
      0.0
      0.0
..     ...
—      0.0
‚      0.0
‡      0.0
‹      0.0
›      0.0

[126 rows x 1 columns]

In [ ]:
df.sort_values(by=['TF-IDF'],ascending=False)


TF-IDF
7   0.591293
5   0.566900
z   0.336798
k   0.291843
d   0.285421
..       ...
;   0.000000
9   0.000000
8   0.000000
6   0.000000
›   0.000000

[126 rows x 1 columns]

Machine Learning Models

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.shape


(535711, 126)

Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0,multi_class='multinomial')

In [ ]:
classifier.fit(X_train,y_train)


LogisticRegression(multi_class='multinomial', random_state=0)

In [ ]:
# Predicting results using logistic regression
d = np.array(['%@123abcd'])
pred = vectorizer.transform(d)
classifier.predict(pred)

array([1])

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, ..., 2, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 5273 12540    10]
 [ 3761 92970  2579]
 [   34  5230 11531]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.58      0.30      0.39     17823
           1       0.84      0.94      0.89     99310
           2       0.82      0.69      0.75     16795

    accuracy                           0.82    133928
   macro avg       0.75      0.64      0.67    133928
weighted avg       0.80      0.82      0.80    133928



In [ ]:
# evaluation metrics
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
acc=accuracy_score(y_test,y_pred)
print("Accuracy is:",acc)

prec = precision_score(y_test, y_pred,average='macro')
print("Precision:", prec)

recall = recall_score(y_test, y_pred, average='macro')
print("Recall:", recall)

f1 = f1_score(y_test, y_pred, average='macro')
print("F1 Score:", f1)

Accuracy is: 0.8196493638372857
Precision: 0.7458908238414166
Recall: 0.6395288525703671
F1 Score: 0.6744581805347697


check password strength using logistic regression

> Add blockquote



In [ ]:
import getpass
user = 'abc'
data = vectorizer.transform([user]).toarray()
output = classifier.predict(data)
if output==0:
    print("Weak Password")
elif output==1:
    print("Moderate strength Password")
else:
    print("Great Password")


Weak Password


In [ ]:
import getpass
user = 'a1b2@c3d4e5'
data = vectorizer.transform([user]).toarray()
output = classifier.predict(data)
if output==0:
    print("Weak Password")
elif output==1:
    print("Moderate strength Password")
else:
    print("Great Password")

Great Password


In [ ]:
import getpass
user = 'abc456'
data = vectorizer.transform([user]).toarray()
output = classifier.predict(data)
if output==0:
    print("Weak Password")
elif output==1:
    print("Moderate strength Password")
else:
    print("Great Password")

Moderate strength Password


Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
d = np.array(['%@123abcd'])
pred = vectorizer.transform(d)
rf.predict(pred)

array([2])

In [ ]:
y_pred2 = rf.predict(X_test)
y_pred2

array([0, 0, 1, ..., 2, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred2)
print(cm)

[[16697  1124     2]
 [  252 98885   173]
 [   11   486 16298]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96     17823
           1       0.98      1.00      0.99     99310
           2       0.99      0.97      0.98     16795

    accuracy                           0.98    133928
   macro avg       0.99      0.97      0.98    133928
weighted avg       0.98      0.98      0.98    133928



In [ ]:
# evaluation metrics
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
acc=accuracy_score(y_test,y_pred2)
print("Accuracy is:",acc)

prec = precision_score(y_test, y_pred2,average='macro')
print("Precision:", prec)

recall = recall_score(y_test, y_pred2, average='macro')
print("Recall:", recall)

f1 = f1_score(y_test, y_pred2, average='macro')
print("F1 Score:", f1)

Accuracy is: 0.9847082014216594
Precision: 0.9859495941856503
Recall: 0.9676505122344797
F1 Score: 0.9765607259146115


check password strength

In [ ]:
import getpass
user = 'abc'
data = vectorizer.transform([user]).toarray()
output = rf.predict(data)
if output==0:
    print("Weak Password")
elif output==1:
    print("Moderate strength Password")
else:
    print("Great Password")

Moderate strength Password


Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=3,min_samples_leaf=35)
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=35)

In [ ]:
d = np.array(['%@123abcd'])
pred = vectorizer.transform(d)
dt.predict(pred)

array([2])

In [ ]:
y_pred3 = dt.predict(X_test)
y_pred3

array([1, 1, 1, ..., 2, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred3)
print(cm)

[[    0 17268   555]
 [    0 95815  3495]
 [    0  7498  9297]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00     17823
           1       0.79      0.96      0.87     99310
           2       0.70      0.55      0.62     16795

    accuracy                           0.78    133928
   macro avg       0.50      0.51      0.50    133928
weighted avg       0.68      0.78      0.72    133928



In [ ]:
# evaluation metrics
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
acc=accuracy_score(y_test,y_pred3)
print("Accuracy is:",acc)

prec = precision_score(y_test, y_pred3,average='macro')
print("Precision:", prec)

recall = recall_score(y_test, y_pred3, average='macro')
print("Recall:", recall)

f1 = f1_score(y_test, y_pred3, average='macro')
print("F1 Score:", f1)

Accuracy is: 0.784839615315692
Precision: 0.4970573720830171
Recall: 0.5061215919666079
F1 Score: 0.4961191109190695


check password strength

In [ ]:
import getpass
user = 'abc'
data = vectorizer.transform([user]).toarray()
output = dt.predict(data)
if output==0:
    print("Weak Password")
elif output==1:
    print("Moderate strength Password")
else:
    print("Great Password")


Moderate strength Password


KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kneigh=KNeighborsClassifier()
kneigh.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
d = np.array(['%@123abcd'])
pred = vectorizer.transform(d)
kneigh.predict(pred)

array([2])

In [ ]:
y_pred4 = kneigh.predict(X_test)
y_pred4

array([1, 1, 1, ..., 2, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred4)
print(cm)

[[10457  7217   149]
 [ 7319 90133  1858]
 [  594  4713 11488]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.57      0.59      0.58     17823
           1       0.88      0.91      0.90     99310
           2       0.85      0.68      0.76     16795

    accuracy                           0.84    133928
   macro avg       0.77      0.73      0.74    133928
weighted avg       0.84      0.84      0.84    133928



In [ ]:
# evaluation metrics
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
acc=accuracy_score(y_test,y_pred4)
print("Accuracy is:",acc)

prec = precision_score(y_test, y_pred4,average='macro')
print("Precision:", prec)

recall = recall_score(y_test, y_pred4, average='macro')
print("Recall:", recall)

f1 = f1_score(y_test, y_pred4, average='macro')
print("F1 Score:", f1)

Accuracy is: 0.8368526372379189
Precision: 0.767877664767351
Recall: 0.7261064277965525
F1 Score: 0.7438550908714113


check password strength

In [ ]:
import getpass
user = 'abc'
data = vectorizer.transform([user]).toarray()
output = kneigh.predict(data)
if output==0:
    print("Weak Password")
elif output==1:
    print("Moderate strength Password")
else:
    print("Great Password")

Weak Password


graph showing accuracy for the models

In [ ]:
mod=[classifier,
     rf,
     dt,
     kneigh]
for m in mod:
  nam=m.__class__.__name__
  y_pred=m.predict(X_test)
  acc=accuracy_score(y_test,y_pred)
  print(nam+':')
  print('Accuracy:{:.4f}'.format(acc))

LogisticRegression:
Accuracy:0.8196
RandomForestClassifier:
Accuracy:0.9847
DecisionTreeClassifier:
Accuracy:0.7848


In [ ]:
r=pd.DataFrame(columns=['Model','Accuracy'])

for m in model:
  nam = m.__class__.__name__
  y_pred = m.predict(X_test)
  acc = accuracy_score(y_test, y_pred)
  r = r.append({'Model': nam, 'Accuracy': acc * 100}, ignore_index=True)

sns.barplot(x='Accuracy', y='Model', data=res, color='b')
plt.xlabel('Accuracy')
plt.title('Accuracy ratio')